### ISSUE TITLE
runPrep.sh misses .simg containers

### ISSUE THREAD

**Issue by caugolm** [ftdc-picsl/pmacsPreps#1]
I am setting up to use runPrep.sh if possible to run aslprep-0.6.0rc1, which is saved as a .simg in containers/, but runPrep.sh doesn't currently find it.
Most local singularity images are saved with ".sif" extensions, but some are ".simg". The ones saved as .simg get missed by runPrep.sh at line 41: it lists available images in the containers/ dir and greps only .sif. 
Similarly, line 202 defines the "image" variable using only the .sif extension

**Comment by cookpa** [comment]
Is there a use case for simg files? I thought sif was preferred

**Comment by caugolm** [comment]
Not that I’m aware of. Older versions of ASLPREP used simg in their singularity examples so that’s what I’d created previously. I’m happy to change that moving forward.
